AWSTemplateFormatVersion: "2010-09-09"
Description: "SageMaker Notebook Instance with workshop prereqs installed"
Resources:
  MyLifecycleConfig:
    Type: AWS::SageMaker::NotebookInstanceLifecycleConfig
    Properties:
      NotebookInstanceLifecycleConfigName:
        !Join ["-", ["NotebookLifeCycle", !Ref "AWS::StackName"]]
      OnCreate:
        - Content:
            Fn::Base64: >-
              #!/bin/bash

              set -e

              cd /home/ec2-user/SageMaker

              ## 2020-05-14 externalize the launch to github/utils/sm-launch.sh

              git clone https://github.com/jwnichols3/aws-immersion-ml-public.git aws-ml-workshop

              sudo chown ec2-user:ec2-user -R aws-ml-workshop/

              chmod +x aws-ml-workshop/utils/*.sh

              nohup sudo aws-ml-workshop/utils/sm-launch.sh > sm-launch.out 2> sm-launch.err &

      OnStart:
        - Content:
            Fn::Base64: >-
              #!/bin/bash

              set -e

              cd /home/ec2-user/SageMaker/aws-ml-workshop

              ## 2020-05-14 externalize the start to github/utils/sm-start.sh

              nohup sudo aws-ml-workshop/utils/sm-start.sh > sm-start.out 2> sm-start.err &

  WorkshopNotebookInstance:
    Type: "AWS::SageMaker::NotebookInstance"
    Properties:
      InstanceType: "ml.t3.large"
      RoleArn: !GetAtt ExecutionRole.Arn
      VolumeSizeInGB: 20
      LifecycleConfigName:
        Fn::GetAtt:
          - MyLifecycleConfig
          - NotebookInstanceLifecycleConfigName

  ExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "sagemaker.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "*"
                Resource: "*"

Outputs:
  WorkshopNotebookInstanceId:
    Value: !Ref WorkshopNotebookInstance
