apiVersion: sagemaker.aws.amazon.com/v1
kind: HostingDeployment
metadata:
  name: hosting-deployment
spec:
  region: $AWS_REGION
  productionVariants:
    - variantName: AllTraffic
      modelName: xgboost-model
      initialInstanceCount: 1
      instanceType: ml.r5.large
      initialVariantWeight: 1
  models:
    - name: xgboost-model
      executionRoleArn: $SAGEMAKER_IAM_ROLE
      containers:
        - containerHostname: xgboost
          modelDataUrl: $MODEL_DATA_URL
          image: 433757028032.dkr.ecr.us-west-2.amazonaws.com/xgboost:latest
